/**
 * Pre-bundled Grade 1 sample dataset for GitHub Pages client-side mode.
 * 100% offline, privacy-first.
 */
window.VIBGYOR_STATIC_DATA = {
  "student": {
    "id": 4,
    "student_id": "EN10672780114",
    "name": "Surya Kudva",
    "grade": "Grade I",
    "section": "F",
    "school": "VIBGYOR Kids and High - HSR Layout",
    "academic_year": "2026 - 27",
    "roll_no": "",
    "parent_name": "Vijay Kudva",
    "created_at": "2026-09-22 06:41:32"
  },
  "dates": [
    {
      "date": "2026-09-22",
      "display_date": "22/09/2026",
      "grade": "Grade - 1F",
      "words_of_the_day": [
        "thump",
        "kind"
      ],
      "words_raw": "thump,kind",
      "homework_count": 2,
      "completed_homework_count": 0,
      "has_pending_homework": true
    },
    {
      "date": "2026-09-21",
      "display_date": "21/09/2026",
      "grade": "Grade - 1F",
      "words_of_the_day": [
        "gone",
        "saw"
      ],
      "words_raw": "gone,saw",
      "homework_count": 1,
      "completed_homework_count": 1,
      "has_pending_homework": false
    },
    {
      "date": "2026-09-18",
      "display_date": "18/09/2026",
      "grade": "Grade - 1F",
      "words_of_the_day": [
        "hear",
        "tame"
      ],
      "words_raw": "hear,tame",
      "homework_count": 1,
      "completed_homework_count": 1,
      "has_pending_homework": false
    },
    {
      "date": "2026-09-17",
      "display_date": "17/09/2026",
      "grade": "Grade - 1F",
      "words_of_the_day": [
        "after",
        "what"
      ],
      "words_raw": "after,what",
      "homework_count": 1,
      "completed_homework_count": 1,
      "has_pending_homework": false
    },
    {
      "date": "2026-09-16",
      "display_date": "16/09/2026",
      "grade": "Grade - 1F",
      "words_of_the_day": [
        "pat",
        "kites"
      ],
      "words_raw": "pat,kites",
      "homework_count": 1,
      "completed_homework_count": 1,
      "has_pending_homework": false
    },
    {
      "date": "2026-09-15",
      "display_date": "15/09/2026",
      "grade": "Grade - 1F",
      "words_of_the_day": [
        "things",
        "pick"
      ],
      "words_raw": "things,pick",
      "homework_count": 2,
      "completed_homework_count": 2,
      "has_pending_homework": false
    }
  ],
  "daily": {
    "2026-09-22": {
      "id": 45,
      "student_id": "N",
      "date": "2026-09-22",
      "display_date": "22/09/2026",
      "grade": "Grade - 1F",
      "words_of_the_day": [
        "thump",
        "kind"
      ],
      "words_raw": "thump,kind",
      "teacher_note": "",
      "source_pdf": "1_F_22_nd_September_1790058218504.pdf",
      "total_periods": 10,
      "homework_count": 2,
      "completed_homework_count": 0,
      "all_homework_completed": false,
      "periods": [
        {
          "id": 441,
          "update_id": 45,
          "date": "2026-09-22",
          "period_number": 1,
          "subject": "Language Arts",
          "topic": "Fluffy has a Bath",
          "sub_topic": "Subject and Predicate",
          "cw": "NIL",
          "reinforcement": "NIL",
          "submission_date": "NIL",
          "submission_date_iso": null,
          "skill_assessed": "NIL",
          "is_homework": false,
          "is_completed": false,
          "completed_at": null,
          "created_at": "2026-09-22 06:40:07"
        },
        {
          "id": 442,
          "update_id": 45,
          "date": "2026-09-22",
          "period_number": 2,
          "subject": "Hindi",
          "topic": "Madhuban",
          "sub_topic": "Introduction to Vyanjan 'jha'",
          "cw": "NIL",
          "reinforcement": "NIL",
          "submission_date": "NIL",
          "submission_date_iso": null,
          "skill_assessed": "Collaboration",
          "is_homework": false,
          "is_completed": false,
          "completed_at": null,
          "created_at": "2026-09-22 06:40:07"
        },
        {
          "id": 443,
          "update_id": 45,
          "date": "2026-09-22",
          "period_number": 3,
          "subject": "Kannada",
          "topic": "Vyanjanagalu",
          "sub_topic": "Ya to La Vyanjanagalu",
          "cw": "NIL",
          "reinforcement": "NIL",
          "submission_date": "NIL",
          "submission_date_iso": null,
          "skill_assessed": "NIL",
          "is_homework": false,
          "is_completed": false,
          "completed_at": null,
          "created_at": "2026-09-22 06:40:07"
        },
        {
          "id": 444,
          "update_id": 45,
          "date": "2026-09-22",
          "period_number": 4,
          "subject": "English Literature",
          "topic": "The Cat in the Hat",
          "sub_topic": "Movie: The Cat In The Hat",
          "cw": "NIL",
          "reinforcement": "NIL",
          "submission_date": "NIL",
          "submission_date_iso": null,
          "skill_assessed": "NIL",
          "is_homework": false,
          "is_completed": false,
          "completed_at": null,
          "created_at": "2026-09-22 06:40:07"
        },
        {
          "id": 445,
          "update_id": 45,
          "date": "2026-09-22",
          "period_number": 5,
          "subject": "Mathematics",
          "topic": "Subtraction",
          "sub_topic": "Revision",
          "cw": "NIL",
          "reinforcement": "NIL",
          "submission_date": "NIL",
          "submission_date_iso": null,
          "skill_assessed": "NIL",
          "is_homework": false,
          "is_completed": false,
          "completed_at": null,
          "created_at": "2026-09-22 06:40:07"
        },
        {
          "id": 446,
          "update_id": 45,
          "date": "2026-09-22",
          "period_number": 6,
          "subject": "Skill Program",
          "topic": "Financial Literacy",
          "sub_topic": "Recognising Notes and Coins",
          "cw": "NIL",
          "reinforcement": "NIL",
          "submission_date": "NIL",
          "submission_date_iso": null,
          "skill_assessed": "NIL",
          "is_homework": false,
          "is_completed": false,
          "completed_at": null,
          "created_at": "2026-09-22 06:40:07"
        },
        {
          "id": 447,
          "update_id": 45,
          "date": "2026-09-22",
          "period_number": 7,
          "subject": "Skill Program",
          "topic": "Financial Literacy",
          "sub_topic": "Recognising Notes and Coins",
          "cw": "NIL",
          "reinforcement": "NIL",
          "submission_date": "NIL",
          "submission_date_iso": null,
          "skill_assessed": "NIL",
          "is_homework": false,
          "is_completed": false,
          "completed_at": null,
          "created_at": "2026-09-22 06:40:07"
        },
        {
          "id": 448,
          "update_id": 45,
          "date": "2026-09-22",
          "period_number": 8,
          "subject": "Computers",
          "topic": "Meet the Computer Mouse",
          "sub_topic": "Revision worksheet",
          "cw": "NIL",
          "reinforcement": "NIL",
          "submission_date": "NIL",
          "submission_date_iso": null,
          "skill_assessed": "NIL",
          "is_homework": false,
          "is_completed": false,
          "completed_at": null,
          "created_at": "2026-09-22 06:40:07"
        },
        {
          "id": 449,
          "update_id": 45,
          "date": "2026-09-22",
          "period_number": 9,
          "subject": "Social Science",
          "topic": "Animals Around Me",
          "sub_topic": "Animals: Where do they live?",
          "cw": "CWSH-23,24,25",
          "reinforcement": "RW-16,17",
          "submission_date": "28/9/26",
          "submission_date_iso": null,
          "skill_assessed": "NIL",
          "is_homework": true,
          "is_completed": false,
          "completed_at": null,
          "created_at": "2026-09-22 06:40:07"
        },
        {
          "id": 450,
          "update_id": 45,
          "date": "2026-09-22",
          "period_number": 10,
          "subject": "Social Science",
          "topic": "Animals Around Me",
          "sub_topic": "Animals: Where do they live?",
          "cw": "CWSH-23,24,25",
          "reinforcement": "RW-16,17",
          "submission_date": "28/9/26",
          "submission_date_iso": null,
          "skill_assessed": "NIL",
          "is_homework": true,
          "is_completed": false,
          "completed_at": null,
          "created_at": "2026-09-22 06:40:07"
        }
      ]
    },
    "2026-09-21": {
      "id": 2,
      "student_id": "VIB-2026-1F-042",
      "date": "2026-09-21",
      "display_date": "21/09/2026",
      "grade": "Grade - 1F",
      "words_of_the_day": [
        "gone",
        "saw"
      ],
      "words_raw": "gone,saw",
      "teacher_note": "",
      "source_pdf": "sample_2026-09-21.pdf",
      "total_periods": 10,
      "homework_count": 1,
      "completed_homework_count": 1,
      "all_homework_completed": true,
      "periods": [
        {
          "id": 11,
          "update_id": 2,
          "date": "2026-09-21",
          "period_number": 1,
          "subject": "Language Arts",
          "topic": "Fluffy has a Bath",
          "sub_topic": "Comprehension",
          "cw": "24A,B,C & D",
          "reinforcement": "NIL",
          "submission_date": "NIL",
          "submission_date_iso": null,
          "skill_assessed": "NIL",
          "is_homework": false,
          "is_completed": false,
          "completed_at": null,
          "created_at": "2026-09-22 04:38:29"
        },
        {
          "id": 12,
          "update_id": 2,
          "date": "2026-09-21",
          "period_number": 2,
          "subject": "Mathematics",
          "topic": "Mental Math",
          "sub_topic": "Revision",
          "cw": "NIL",
          "reinforcement": "NIL",
          "submission_date": "NIL",
          "submission_date_iso": null,
          "skill_assessed": "Computational fluency",
          "is_homework": false,
          "is_completed": false,
          "completed_at": null,
          "created_at": "2026-09-22 04:38:29"
        },
        {
          "id": 13,
          "update_id": 2,
          "date": "2026-09-21",
          "period_number": 3,
          "subject": "SPA",
          "topic": "NIL",
          "sub_topic": "NIL",
          "cw": "NIL",
          "reinforcement": "NIL",
          "submission_date": "NIL",
          "submission_date_iso": null,
          "skill_assessed": "NIL",
          "is_homework": false,
          "is_completed": false,
          "completed_at": null,
          "created_at": "2026-09-22 04:38:29"
        },
        {
          "id": 14,
          "update_id": 2,
          "date": "2026-09-21",
          "period_number": 4,
          "subject": "SPA",
          "topic": "NIL",
          "sub_topic": "NIL",
          "cw": "NIL",
          "reinforcement": "NIL",
          "submission_date": "NIL",
          "submission_date_iso": null,
          "skill_assessed": "NIL",
          "is_homework": false,
          "is_completed": false,
          "completed_at": null,
          "created_at": "2026-09-22 04:38:29"
        },
        {
          "id": 15,
          "update_id": 2,
          "date": "2026-09-21",
          "period_number": 5,
          "subject": "Kannada",
          "topic": "Vyanjanagalu",
          "sub_topic": "Pa to Ma Vyanjanagalu",
          "cw": "NIL",
          "reinforcement": "NIL",
          "submission_date": "NIL",
          "submission_date_iso": null,
          "skill_assessed": "NIL",
          "is_homework": false,
          "is_completed": false,
          "completed_at": null,
          "created_at": "2026-09-22 04:38:29"
        },
        {
          "id": 16,
          "update_id": 2,
          "date": "2026-09-21",
          "period_number": 6,
          "subject": "Mathematics",
          "topic": "Mental Math",
          "sub_topic": "Revision",
          "cw": "NIL",
          "reinforcement": "NIL",
          "submission_date": "NIL",
          "submission_date_iso": null,
          "skill_assessed": "Computational fluency",
          "is_homework": false,
          "is_completed": false,
          "completed_at": null,
          "created_at": "2026-09-22 04:38:29"
        },
        {
          "id": 17,
          "update_id": 2,
          "date": "2026-09-21",
          "period_number": 7,
          "subject": "Robotics",
          "topic": "Project 3: Windy Wonder Machine",
          "sub_topic": "Concept Exploration",
          "cw": "NIL",
          "reinforcement": "To practice and complete Tinkercad project 3 from pages 25-28",
          "submission_date": "NIL",
          "submission_date_iso": null,
          "skill_assessed": "NIL",
          "is_homework": true,
          "is_completed": true,
          "completed_at": "2026-09-22T18:52:56.285754",
          "created_at": "2026-09-22 04:38:29"
        },
        {
          "id": 18,
          "update_id": 2,
          "date": "2026-09-21",
          "period_number": 8,
          "subject": "English Literature",
          "topic": "The Cat in the Hat",
          "sub_topic": "Movie: The Cat In The Hat",
          "cw": "NIL",
          "reinforcement": "NIL",
          "submission_date": "NIL",
          "submission_date_iso": null,
          "skill_assessed": "NIL",
          "is_homework": false,
          "is_completed": false,
          "completed_at": null,
          "created_at": "2026-09-22 04:38:29"
        },
        {
          "id": 19,
          "update_id": 2,
          "date": "2026-09-21",
          "period_number": 9,
          "subject": "Social Science",
          "topic": "Animals Around Me",
          "sub_topic": "Recap of Insect Life",
          "cw": "NIL",
          "reinforcement": "NIL",
          "submission_date": "NIL",
          "submission_date_iso": null,
          "skill_assessed": "NIL",
          "is_homework": false,
          "is_completed": false,
          "completed_at": null,
          "created_at": "2026-09-22 04:38:29"
        },
        {
          "id": 20,
          "update_id": 2,
          "date": "2026-09-21",
          "period_number": 10,
          "subject": "Social Science",
          "topic": "Animals Around Me",
          "sub_topic": "Recap of Insect Life",
          "cw": "NIL",
          "reinforcement": "NIL",
          "submission_date": "NIL",
          "submission_date_iso": null,
          "skill_assessed": "NIL",
          "is_homework": false,
          "is_completed": false,
          "completed_at": null,
          "created_at": "2026-09-22 04:38:29"
        }
      ]
    },
    "2026-09-18": {
      "id": 1,
      "student_id": "VIB-2026-1F-042",
      "date": "2026-09-18",
      "display_date": "18/09/2026",
      "grade": "Grade - 1F",
      "words_of_the_day": [
        "hear",
        "tame"
      ],
      "words_raw": "hear,tame",
      "teacher_note": "Kindly help your ward revise the topic of Addition in Mathematics. Please refer to the VExplore book and reinforcement worksheets for practice.",
      "source_pdf": "sample_2026-09-18.pdf",
      "total_periods": 10,
      "homework_count": 1,
      "completed_homework_count": 1,
      "all_homework_completed": true,
      "periods": [
        {
          "id": 1,
          "update_id": 1,
          "date": "2026-09-18",
          "period_number": 1,
          "subject": "Kannada",
          "topic": "Vyanjanagalu",
          "sub_topic": "Revision of Vyanjanagalu",
          "cw": "NIL",
          "reinforcement": "NIL",
          "submission_date": "NIL",
          "submission_date_iso": null,
          "skill_assessed": "NIL",
          "is_homework": false,
          "is_completed": false,
          "completed_at": null,
          "created_at": "2026-09-22 04:38:29"
        },
        {
          "id": 2,
          "update_id": 1,
          "date": "2026-09-18",
          "period_number": 2,
          "subject": "Computers",
          "topic": "Meet the Computer Mouse",
          "sub_topic": "Practical Activity",
          "cw": "NIL",
          "reinforcement": "NIL",
          "submission_date": "NIL",
          "submission_date_iso": null,
          "skill_assessed": "NIL",
          "is_homework": false,
          "is_completed": false,
          "completed_at": null,
          "created_at": "2026-09-22 04:38:29"
        },
        {
          "id": 3,
          "update_id": 1,
          "date": "2026-09-18",
          "period_number": 3,
          "subject": "English Literature",
          "topic": "The Cat in the Hat",
          "sub_topic": "Movie: The Cat In The Hat",
          "cw": "NIL",
          "reinforcement": "NIL",
          "submission_date": "NIL",
          "submission_date_iso": null,
          "skill_assessed": "NIL",
          "is_homework": false,
          "is_completed": false,
          "completed_at": null,
          "created_at": "2026-09-22 04:38:29"
        },
        {
          "id": 4,
          "update_id": 1,
          "date": "2026-09-18",
          "period_number": 4,
          "subject": "Enrichment program",
          "topic": "IHC-3",
          "sub_topic": "NIL",
          "cw": "NIL",
          "reinforcement": "NIL",
          "submission_date": "NIL",
          "submission_date_iso": null,
          "skill_assessed": "NIL",
          "is_homework": false,
          "is_completed": false,
          "completed_at": null,
          "created_at": "2026-09-22 04:38:29"
        },
        {
          "id": 5,
          "update_id": 1,
          "date": "2026-09-18",
          "period_number": 5,
          "subject": "Hindi",
          "topic": "Madhuban",
          "sub_topic": "Introduction to Vyanjan 'ja'",
          "cw": "NIL",
          "reinforcement": "NIL",
          "submission_date": "NIL",
          "submission_date_iso": null,
          "skill_assessed": "Collaboration",
          "is_homework": false,
          "is_completed": false,
          "completed_at": null,
          "created_at": "2026-09-22 04:38:29"
        },
        {
          "id": 6,
          "update_id": 1,
          "date": "2026-09-18",
          "period_number": 6,
          "subject": "Mathematics",
          "topic": "Addition",
          "sub_topic": "Revision",
          "cw": "NIL",
          "reinforcement": "NIL",
          "submission_date": "NIL",
          "submission_date_iso": null,
          "skill_assessed": "NIL",
          "is_homework": false,
          "is_completed": false,
          "completed_at": null,
          "created_at": "2026-09-22 04:38:29"
        },
        {
          "id": 7,
          "update_id": 1,
          "date": "2026-09-18",
          "period_number": 7,
          "subject": "Social Science",
          "topic": "Animals Around Me",
          "sub_topic": "Insect Life: Introduction to insects, parts of a body",
          "cw": "NIL",
          "reinforcement": "RWSH-14,15",
          "submission_date": "21/09/2026",
          "submission_date_iso": "2026-09-21",
          "skill_assessed": "Experiential Learning",
          "is_homework": true,
          "is_completed": true,
          "completed_at": "2026-09-22T19:19:58.282511",
          "created_at": "2026-09-22 04:38:29"
        },
        {
          "id": 8,
          "update_id": 1,
          "date": "2026-09-18",
          "period_number": 8,
          "subject": "Social Science",
          "topic": "Animals Around Me",
          "sub_topic": "Animals: Where do they live?",
          "cw": "CWSH-22",
          "reinforcement": "NIL",
          "submission_date": "NIL",
          "submission_date_iso": null,
          "skill_assessed": "NIL",
          "is_homework": false,
          "is_completed": false,
          "completed_at": null,
          "created_at": "2026-09-22 04:38:29"
        },
        {
          "id": 9,
          "update_id": 1,
          "date": "2026-09-18",
          "period_number": 9,
          "subject": "Language Arts",
          "topic": "Revision",
          "sub_topic": "Recap of Sentence Structure",
          "cw": "NIL",
          "reinforcement": "NIL",
          "submission_date": "NIL",
          "submission_date_iso": null,
          "skill_assessed": "NIL",
          "is_homework": false,
          "is_completed": false,
          "completed_at": null,
          "created_at": "2026-09-22 04:38:29"
        },
        {
          "id": 10,
          "update_id": 1,
          "date": "2026-09-18",
          "period_number": 10,
          "subject": "English Literature",
          "topic": "The Cat in the Hat",
          "sub_topic": "Recap on poem comprehension",
          "cw": "NIL",
          "reinforcement": "NIL",
          "submission_date": "NIL",
          "submission_date_iso": null,
          "skill_assessed": "NIL",
          "is_homework": false,
          "is_completed": false,
          "completed_at": null,
          "created_at": "2026-09-22 04:38:29"
        }
      ]
    },
    "2026-09-17": {
      "id": 48,
      "student_id": "N",
      "date": "2026-09-17",
      "display_date": "17/09/2026",
      "grade": "Grade - 1F",
      "words_of_the_day": [
        "after",
        "what"
      ],
      "words_raw": "after,what",
      "teacher_note": "Kindly help your ward revise the topic of Addition in Mathematics. Please refer to the VExplore book and reinforcement worksheets for practice.\n\nGentle reminder for Inter House Competition-3 which will be held on Friday(18 -September- 2026). Theme : Fancy Dress (Fairy Tale / Cartoon Character ) Category : Individual Competition Please note children should introduce themselves by saying a few lines (not more than one minute). Kindly send a note in Student Handbook if your child wishes to participate in the competition.",
      "source_pdf": "1_F_17_th_September_1789632114673.pdf",
      "total_periods": 10,
      "homework_count": 1,
      "completed_homework_count": 1,
      "all_homework_completed": true,
      "periods": [
        {
          "id": 471,
          "update_id": 48,
          "date": "2026-09-17",
          "period_number": 1,
          "subject": "Assembly",
          "topic": "NIL",
          "sub_topic": "NIL",
          "cw": "NIL",
          "reinforcement": "NIL",
          "submission_date": "NIL",
          "submission_date_iso": null,
          "skill_assessed": "NIL",
          "is_homework": false,
          "is_completed": false,
          "completed_at": null,
          "created_at": "2026-09-22 06:40:09"
        },
        {
          "id": 472,
          "update_id": 48,
          "date": "2026-09-17",
          "period_number": 2,
          "subject": "Language Arts",
          "topic": "Revision",
          "sub_topic": "Nil",
          "cw": "NIL",
          "reinforcement": "NIL",
          "submission_date": "NIL",
          "submission_date_iso": null,
          "skill_assessed": "NIL",
          "is_homework": false,
          "is_completed": false,
          "completed_at": null,
          "created_at": "2026-09-22 06:40:09"
        },
        {
          "id": 473,
          "update_id": 48,
          "date": "2026-09-17",
          "period_number": 3,
          "subject": "Language Arts",
          "topic": "Revision",
          "sub_topic": "Nil",
          "cw": "NIL",
          "reinforcement": "NIL",
          "submission_date": "NIL",
          "submission_date_iso": null,
          "skill_assessed": "NIL",
          "is_homework": false,
          "is_completed": false,
          "completed_at": null,
          "created_at": "2026-09-22 06:40:09"
        },
        {
          "id": 474,
          "update_id": 48,
          "date": "2026-09-17",
          "period_number": 4,
          "subject": "Mathematics",
          "topic": "Subtraction",
          "sub_topic": "subtraction (counting backwards)",
          "cw": "CWSH-33A,33B",
          "reinforcement": "RWSH-32,33A,33B",
          "submission_date": "23/09/2026",
          "submission_date_iso": "2026-09-23",
          "skill_assessed": "Collaboration",
          "is_homework": true,
          "is_completed": true,
          "completed_at": "2026-09-22T18:52:48.261092",
          "created_at": "2026-09-22 06:40:09"
        },
        {
          "id": 475,
          "update_id": 48,
          "date": "2026-09-17",
          "period_number": 5,
          "subject": "SPA",
          "topic": "NIL",
          "sub_topic": "NIL",
          "cw": "NIL",
          "reinforcement": "NIL",
          "submission_date": "NIL",
          "submission_date_iso": null,
          "skill_assessed": "NIL",
          "is_homework": false,
          "is_completed": false,
          "completed_at": null,
          "created_at": "2026-09-22 06:40:09"
        },
        {
          "id": 476,
          "update_id": 48,
          "date": "2026-09-17",
          "period_number": 6,
          "subject": "SPA",
          "topic": "NIL",
          "sub_topic": "NIL",
          "cw": "NIL",
          "reinforcement": "NIL",
          "submission_date": "NIL",
          "submission_date_iso": null,
          "skill_assessed": "NIL",
          "is_homework": false,
          "is_completed": false,
          "completed_at": null,
          "created_at": "2026-09-22 06:40:09"
        },
        {
          "id": 477,
          "update_id": 48,
          "date": "2026-09-17",
          "period_number": 7,
          "subject": "Art",
          "topic": "Revision of Primary and Secondery Colour",
          "sub_topic": "Revision of Primary and Secondery Colour",
          "cw": "NIL",
          "reinforcement": "NIL",
          "submission_date": "NIL",
          "submission_date_iso": null,
          "skill_assessed": "NIL",
          "is_homework": false,
          "is_completed": false,
          "completed_at": null,
          "created_at": "2026-09-22 06:40:09"
        },
        {
          "id": 478,
          "update_id": 48,
          "date": "2026-09-17",
          "period_number": 8,
          "subject": "Art",
          "topic": "Revision of Primary and Secondery Colour",
          "sub_topic": "Revision of Primary and Secondery Colour",
          "cw": "NIL",
          "reinforcement": "NIL",
          "submission_date": "NIL",
          "submission_date_iso": null,
          "skill_assessed": "NIL",
          "is_homework": false,
          "is_completed": false,
          "completed_at": null,
          "created_at": "2026-09-22 06:40:09"
        },
        {
          "id": 479,
          "update_id": 48,
          "date": "2026-09-17",
          "period_number": 9,
          "subject": "English Literature",
          "topic": "The Cat in the Hat",
          "sub_topic": "Recap on poem comprehension",
          "cw": "NIL",
          "reinforcement": "NIL",
          "submission_date": "NIL",
          "submission_date_iso": null,
          "skill_assessed": "NIL",
          "is_homework": false,
          "is_completed": false,
          "completed_at": null,
          "created_at": "2026-09-22 06:40:09"
        },
        {
          "id": 480,
          "update_id": 48,
          "date": "2026-09-17",
          "period_number": 10,
          "subject": "Social Science",
          "topic": "Animals Around Me",
          "sub_topic": "Insect Life: Introduction to insects, parts of a body",
          "cw": "NIL",
          "reinforcement": "NIL",
          "submission_date": "NIL",
          "submission_date_iso": null,
          "skill_assessed": "NIL",
          "is_homework": false,
          "is_completed": false,
          "completed_at": null,
          "created_at": "2026-09-22 06:40:09"
        }
      ]
    },
    "2026-09-16": {
      "id": 49,
      "student_id": "N",
      "date": "2026-09-16",
      "display_date": "16/09/2026",
      "grade": "Grade - 1F",
      "words_of_the_day": [
        "pat",
        "kites"
      ],
      "words_raw": "pat,kites",
      "teacher_note": "Kindly help your ward revise the topic of Addition in Mathematics. Please refer to the VExplore book and reinforcement worksheets for practice.\n\nKindly assist your ward in revising Naming words, Noun helpers,Action words,Verbs(Subject-Verb Agreement), Being verbs, Sentence Structure, long vowel sounds,' r ' controlled vowels,  final 'e' words in Language Arts.\n\nGentle reminder for Inter House Competition-3 which will be held on Friday(18 -September- 2026). Theme : Fancy Dress (Fairy Tale / Cartoon Character ) Category : Individual Competition Please note children should introduce themselves by saying a few lines (not more than one minute). Kindly send a note in Student Handbook if your child wishes to participate in the competition.",
      "source_pdf": "1_F_16_th_September_1789539459955.pdf",
      "total_periods": 9,
      "homework_count": 1,
      "completed_homework_count": 1,
      "all_homework_completed": true,
      "periods": [
        {
          "id": 481,
          "update_id": 49,
          "date": "2026-09-16",
          "period_number": 1,
          "subject": "Language Arts",
          "topic": "Revision",
          "sub_topic": "Recap of Sentence structure and long vowel sounds",
          "cw": "NIL",
          "reinforcement": "NIL",
          "submission_date": "NIL",
          "submission_date_iso": null,
          "skill_assessed": "NIL",
          "is_homework": false,
          "is_completed": false,
          "completed_at": null,
          "created_at": "2026-09-22 06:40:09"
        },
        {
          "id": 482,
          "update_id": 49,
          "date": "2026-09-16",
          "period_number": 2,
          "subject": "Library",
          "topic": "Story Telling",
          "sub_topic": "Words given",
          "cw": "NIL",
          "reinforcement": "NIL",
          "submission_date": "NIL",
          "submission_date_iso": null,
          "skill_assessed": "NIL",
          "is_homework": false,
          "is_completed": false,
          "completed_at": null,
          "created_at": "2026-09-22 06:40:09"
        },
        {
          "id": 483,
          "update_id": 49,
          "date": "2026-09-16",
          "period_number": 3,
          "subject": "SPA",
          "topic": "NIL",
          "sub_topic": "NIL",
          "cw": "NIL",
          "reinforcement": "NIL",
          "submission_date": "NIL",
          "submission_date_iso": null,
          "skill_assessed": "NIL",
          "is_homework": false,
          "is_completed": false,
          "completed_at": null,
          "created_at": "2026-09-22 06:40:09"
        },
        {
          "id": 484,
          "update_id": 49,
          "date": "2026-09-16",
          "period_number": 4,
          "subject": "SPA",
          "topic": "NIL",
          "sub_topic": "NIL",
          "cw": "NIL",
          "reinforcement": "NIL",
          "submission_date": "NIL",
          "submission_date_iso": null,
          "skill_assessed": "NIL",
          "is_homework": false,
          "is_completed": false,
          "completed_at": null,
          "created_at": "2026-09-22 06:40:09"
        },
        {
          "id": 485,
          "update_id": 49,
          "date": "2026-09-16",
          "period_number": 5,
          "subject": "Social Science",
          "topic": "Animals Around Me",
          "sub_topic": "Insect Life: Introduction to insects, parts of a body",
          "cw": "NIL",
          "reinforcement": "NIL",
          "submission_date": "NIL",
          "submission_date_iso": null,
          "skill_assessed": "NIL",
          "is_homework": false,
          "is_completed": false,
          "completed_at": null,
          "created_at": "2026-09-22 06:40:09"
        },
        {
          "id": 486,
          "update_id": 49,
          "date": "2026-09-16",
          "period_number": 6,
          "subject": "Kannada",
          "topic": "Vyanjanagalu",
          "sub_topic": "Ta to Na Vyanjanagalu",
          "cw": "NIL",
          "reinforcement": "NIL",
          "submission_date": "NIL",
          "submission_date_iso": null,
          "skill_assessed": "NIL",
          "is_homework": false,
          "is_completed": false,
          "completed_at": null,
          "created_at": "2026-09-22 06:40:09"
        },
        {
          "id": 488,
          "update_id": 49,
          "date": "2026-09-16",
          "period_number": 7,
          "subject": "English Literature",
          "topic": "The Cat in the Hat",
          "sub_topic": "Unrealistic Situations",
          "cw": "NIL",
          "reinforcement": "RWSH-6A,B",
          "submission_date": "NIL",
          "submission_date_iso": null,
          "skill_assessed": "NIL",
          "is_homework": true,
          "is_completed": true,
          "completed_at": "2026-09-22T18:52:42.811076",
          "created_at": "2026-09-22 06:40:09"
        },
        {
          "id": 489,
          "update_id": 49,
          "date": "2026-09-16",
          "period_number": 9,
          "subject": "Mathematics",
          "topic": "Subtraction",
          "sub_topic": "subtraction (counting backwards)",
          "cw": "CWSH-32",
          "reinforcement": "NIL",
          "submission_date": "23/09/2026",
          "submission_date_iso": "2026-09-23",
          "skill_assessed": "Collaboration",
          "is_homework": false,
          "is_completed": false,
          "completed_at": null,
          "created_at": "2026-09-22 06:40:09"
        },
        {
          "id": 490,
          "update_id": 49,
          "date": "2026-09-16",
          "period_number": 10,
          "subject": "Language Arts",
          "topic": "Revision",
          "sub_topic": "Recap of Final 'e' words and and 'r' controlled vowels",
          "cw": "NIL",
          "reinforcement": "NIL",
          "submission_date": "NIL",
          "submission_date_iso": null,
          "skill_assessed": "NIL",
          "is_homework": false,
          "is_completed": false,
          "completed_at": null,
          "created_at": "2026-09-22 06:40:09"
        }
      ]
    },
    "2026-09-15": {
      "id": 50,
      "student_id": "N",
      "date": "2026-09-15",
      "display_date": "15/09/2026",
      "grade": "Grade - 1F",
      "words_of_the_day": [
        "things",
        "pick"
      ],
      "words_raw": "things,pick",
      "teacher_note": "Kindly help your ward revise the topic of Addition in Mathematics. Please refer to the VExplore book and reinforcement worksheets for practice.\n\nKindly assist your ward in revising Naming words, Noun helpers,Action words,Verbs(Subject-Verb Agreement), Being verbs, Sentence Structure, long vowel sounds,' r ' controlled vowels,  final 'e' words in Language Arts.",
      "source_pdf": "1_F_15_th_September_1789454304156.pdf",
      "total_periods": 10,
      "homework_count": 2,
      "completed_homework_count": 2,
      "all_homework_completed": true,
      "periods": [
        {
          "id": 491,
          "update_id": 50,
          "date": "2026-09-15",
          "period_number": 1,
          "subject": "Language Arts",
          "topic": "Revision-1",
          "sub_topic": "Revision of the topics done",
          "cw": "23  D, E",
          "reinforcement": "2  A, B ,C (pg no. 15, 16, 17 )",
          "submission_date": "21/09/2026",
          "submission_date_iso": "2026-09-21",
          "skill_assessed": "NIL",
          "is_homework": true,
          "is_completed": true,
          "completed_at": "2026-09-22T18:52:34.394857",
          "created_at": "2026-09-22 06:40:10"
        },
        {
          "id": 492,
          "update_id": 50,
          "date": "2026-09-15",
          "period_number": 2,
          "subject": "Hindi",
          "topic": "Madhuban",
          "sub_topic": "Introduction to Vyanjan 'chha'",
          "cw": "NIL",
          "reinforcement": "NIL",
          "submission_date": "NIL",
          "submission_date_iso": null,
          "skill_assessed": "Collaboration",
          "is_homework": false,
          "is_completed": false,
          "completed_at": null,
          "created_at": "2026-09-22 06:40:10"
        },
        {
          "id": 493,
          "update_id": 50,
          "date": "2026-09-15",
          "period_number": 3,
          "subject": "Kannada",
          "topic": "Vyanjanagalu",
          "sub_topic": "Ta to Na Vyanjanagalu",
          "cw": "NIL",
          "reinforcement": "NIL",
          "submission_date": "NIL",
          "submission_date_iso": null,
          "skill_assessed": "NIL",
          "is_homework": false,
          "is_completed": false,
          "completed_at": null,
          "created_at": "2026-09-22 06:40:10"
        },
        {
          "id": 494,
          "update_id": 50,
          "date": "2026-09-15",
          "period_number": 4,
          "subject": "English Literature",
          "topic": "The Cat in the Hat",
          "sub_topic": "Imaginary Play things",
          "cw": "NIL",
          "reinforcement": "NIL",
          "submission_date": "NIL",
          "submission_date_iso": null,
          "skill_assessed": "NIL",
          "is_homework": false,
          "is_completed": false,
          "completed_at": null,
          "created_at": "2026-09-22 06:40:10"
        },
        {
          "id": 495,
          "update_id": 50,
          "date": "2026-09-15",
          "period_number": 5,
          "subject": "Mathematics",
          "topic": "Subtraction",
          "sub_topic": "subtraction (counting backwards)",
          "cw": "CWSH-29A, 29B",
          "reinforcement": "RWSH-28",
          "submission_date": "23/09/2026",
          "submission_date_iso": "2026-09-23",
          "skill_assessed": "Computational fluency",
          "is_homework": true,
          "is_completed": true,
          "completed_at": "2026-09-22T18:52:36.502504",
          "created_at": "2026-09-22 06:40:10"
        },
        {
          "id": 496,
          "update_id": 50,
          "date": "2026-09-15",
          "period_number": 6,
          "subject": "Skill Program",
          "topic": "Revision",
          "sub_topic": "Nil",
          "cw": "NIL",
          "reinforcement": "NIL",
          "submission_date": "NIL",
          "submission_date_iso": null,
          "skill_assessed": "NIL",
          "is_homework": false,
          "is_completed": false,
          "completed_at": null,
          "created_at": "2026-09-22 06:40:10"
        },
        {
          "id": 497,
          "update_id": 50,
          "date": "2026-09-15",
          "period_number": 7,
          "subject": "Skill Program",
          "topic": "Revision",
          "sub_topic": "Nil",
          "cw": "NIL",
          "reinforcement": "NIL",
          "submission_date": "NIL",
          "submission_date_iso": null,
          "skill_assessed": "NIL",
          "is_homework": false,
          "is_completed": false,
          "completed_at": null,
          "created_at": "2026-09-22 06:40:10"
        },
        {
          "id": 498,
          "update_id": 50,
          "date": "2026-09-15",
          "period_number": 8,
          "subject": "Computers",
          "topic": "Meet the Computer Mouse",
          "sub_topic": "Practice zone",
          "cw": "NIL",
          "reinforcement": "NIL",
          "submission_date": "NIL",
          "submission_date_iso": null,
          "skill_assessed": "NIL",
          "is_homework": false,
          "is_completed": false,
          "completed_at": null,
          "created_at": "2026-09-22 06:40:10"
        },
        {
          "id": 499,
          "update_id": 50,
          "date": "2026-09-15",
          "period_number": 9,
          "subject": "Social Science",
          "topic": "Animals Around Me",
          "sub_topic": "Bird Kingdom: Activity",
          "cw": "NIL",
          "reinforcement": "NIL",
          "submission_date": "NIL",
          "submission_date_iso": null,
          "skill_assessed": "NIL",
          "is_homework": false,
          "is_completed": false,
          "completed_at": null,
          "created_at": "2026-09-22 06:40:10"
        },
        {
          "id": 500,
          "update_id": 50,
          "date": "2026-09-15",
          "period_number": 10,
          "subject": "Social Science",
          "topic": "Animals Around Me",
          "sub_topic": "Bird Kingdom: Activity",
          "cw": "NIL",
          "reinforcement": "NIL",
          "submission_date": "NIL",
          "submission_date_iso": null,
          "skill_assessed": "NIL",
          "is_homework": false,
          "is_completed": false,
          "completed_at": null,
          "created_at": "2026-09-22 06:40:10"
        }
      ]
    }
  },
  "weekly": {
    "week_start": "2026-09-21",
    "week_end": "2026-09-25",
    "days": [
      {
        "id": 2,
        "student_id": "VIB-2026-1F-042",
        "date": "2026-09-21",
        "display_date": "21/09/2026",
        "grade": "Grade - 1F",
        "words_of_the_day": [
          "gone",
          "saw"
        ],
        "words_raw": "gone,saw",
        "teacher_note": "",
        "source_pdf": "sample_2026-09-21.pdf",
        "total_periods": 10,
        "homework_count": 1,
        "completed_homework_count": 1,
        "all_homework_completed": true,
        "periods": [
          {
            "id": 11,
            "update_id": 2,
            "date": "2026-09-21",
            "period_number": 1,
            "subject": "Language Arts",
            "topic": "Fluffy has a Bath",
            "sub_topic": "Comprehension",
            "cw": "24A,B,C & D",
            "reinforcement": "NIL",
            "submission_date": "NIL",
            "submission_date_iso": null,
            "skill_assessed": "NIL",
            "is_homework": false,
            "is_completed": false,
            "completed_at": null,
            "created_at": "2026-09-22 04:38:29"
          },
          {
            "id": 12,
            "update_id": 2,
            "date": "2026-09-21",
            "period_number": 2,
            "subject": "Mathematics",
            "topic": "Mental Math",
            "sub_topic": "Revision",
            "cw": "NIL",
            "reinforcement": "NIL",
            "submission_date": "NIL",
            "submission_date_iso": null,
            "skill_assessed": "Computational fluency",
            "is_homework": false,
            "is_completed": false,
            "completed_at": null,
            "created_at": "2026-09-22 04:38:29"
          },
          {
            "id": 13,
            "update_id": 2,
            "date": "2026-09-21",
            "period_number": 3,
            "subject": "SPA",
            "topic": "NIL",
            "sub_topic": "NIL",
            "cw": "NIL",
            "reinforcement": "NIL",
            "submission_date": "NIL",
            "submission_date_iso": null,
            "skill_assessed": "NIL",
            "is_homework": false,
            "is_completed": false,
            "completed_at": null,
            "created_at": "2026-09-22 04:38:29"
          },
          {
            "id": 14,
            "update_id": 2,
            "date": "2026-09-21",
            "period_number": 4,
            "subject": "SPA",
            "topic": "NIL",
            "sub_topic": "NIL",
            "cw": "NIL",
            "reinforcement": "NIL",
            "submission_date": "NIL",
            "submission_date_iso": null,
            "skill_assessed": "NIL",
            "is_homework": false,
            "is_completed": false,
            "completed_at": null,
            "created_at": "2026-09-22 04:38:29"
          },
          {
            "id": 15,
            "update_id": 2,
            "date": "2026-09-21",
            "period_number": 5,
            "subject": "Kannada",
            "topic": "Vyanjanagalu",
            "sub_topic": "Pa to Ma Vyanjanagalu",
            "cw": "NIL",
            "reinforcement": "NIL",
            "submission_date": "NIL",
            "submission_date_iso": null,
            "skill_assessed": "NIL",
            "is_homework": false,
            "is_completed": false,
            "completed_at": null,
            "created_at": "2026-09-22 04:38:29"
          },
          {
            "id": 16,
            "update_id": 2,
            "date": "2026-09-21",
            "period_number": 6,
            "subject": "Mathematics",
            "topic": "Mental Math",
            "sub_topic": "Revision",
            "cw": "NIL",
            "reinforcement": "NIL",
            "submission_date": "NIL",
            "submission_date_iso": null,
            "skill_assessed": "Computational fluency",
            "is_homework": false,
            "is_completed": false,
            "completed_at": null,
            "created_at": "2026-09-22 04:38:29"
          },
          {
            "id": 17,
            "update_id": 2,
            "date": "2026-09-21",
            "period_number": 7,
            "subject": "Robotics",
            "topic": "Project 3: Windy Wonder Machine",
            "sub_topic": "Concept Exploration",
            "cw": "NIL",
            "reinforcement": "To practice and complete Tinkercad project 3 from pages 25-28",
            "submission_date": "NIL",
            "submission_date_iso": null,
            "skill_assessed": "NIL",
            "is_homework": true,
            "is_completed": true,
            "completed_at": "2026-09-22T18:52:56.285754",
            "created_at": "2026-09-22 04:38:29"
          },
          {
            "id": 18,
            "update_id": 2,
            "date": "2026-09-21",
            "period_number": 8,
            "subject": "English Literature",
            "topic": "The Cat in the Hat",
            "sub_topic": "Movie: The Cat In The Hat",
            "cw": "NIL",
            "reinforcement": "NIL",
            "submission_date": "NIL",
            "submission_date_iso": null,
            "skill_assessed": "NIL",
            "is_homework": false,
            "is_completed": false,
            "completed_at": null,
            "created_at": "2026-09-22 04:38:29"
          },
          {
            "id": 19,
            "update_id": 2,
            "date": "2026-09-21",
            "period_number": 9,
            "subject": "Social Science",
            "topic": "Animals Around Me",
            "sub_topic": "Recap of Insect Life",
            "cw": "NIL",
            "reinforcement": "NIL",
            "submission_date": "NIL",
            "submission_date_iso": null,
            "skill_assessed": "NIL",
            "is_homework": false,
            "is_completed": false,
            "completed_at": null,
            "created_at": "2026-09-22 04:38:29"
          },
          {
            "id": 20,
            "update_id": 2,
            "date": "2026-09-21",
            "period_number": 10,
            "subject": "Social Science",
            "topic": "Animals Around Me",
            "sub_topic": "Recap of Insect Life",
            "cw": "NIL",
            "reinforcement": "NIL",
            "submission_date": "NIL",
            "submission_date_iso": null,
            "skill_assessed": "NIL",
            "is_homework": false,
            "is_completed": false,
            "completed_at": null,
            "created_at": "2026-09-22 04:38:29"
          }
        ]
      },
      {
        "id": 45,
        "student_id": "N",
        "date": "2026-09-22",
        "display_date": "22/09/2026",
        "grade": "Grade - 1F",
        "words_of_the_day": [
          "thump",
          "kind"
        ],
        "words_raw": "thump,kind",
        "teacher_note": "",
        "source_pdf": "1_F_22_nd_September_1790058218504.pdf",
        "total_periods": 10,
        "homework_count": 2,
        "completed_homework_count": 0,
        "all_homework_completed": false,
        "periods": [
          {
            "id": 441,
            "update_id": 45,
            "date": "2026-09-22",
            "period_number": 1,
            "subject": "Language Arts",
            "topic": "Fluffy has a Bath",
            "sub_topic": "Subject and Predicate",
            "cw": "NIL",
            "reinforcement": "NIL",
            "submission_date": "NIL",
            "submission_date_iso": null,
            "skill_assessed": "NIL",
            "is_homework": false,
            "is_completed": false,
            "completed_at": null,
            "created_at": "2026-09-22 06:40:07"
          },
          {
            "id": 442,
            "update_id": 45,
            "date": "2026-09-22",
            "period_number": 2,
            "subject": "Hindi",
            "topic": "Madhuban",
            "sub_topic": "Introduction to Vyanjan 'jha'",
            "cw": "NIL",
            "reinforcement": "NIL",
            "submission_date": "NIL",
            "submission_date_iso": null,
            "skill_assessed": "Collaboration",
            "is_homework": false,
            "is_completed": false,
            "completed_at": null,
            "created_at": "2026-09-22 06:40:07"
          },
          {
            "id": 443,
            "update_id": 45,
            "date": "2026-09-22",
            "period_number": 3,
            "subject": "Kannada",
            "topic": "Vyanjanagalu",
            "sub_topic": "Ya to La Vyanjanagalu",
            "cw": "NIL",
            "reinforcement": "NIL",
            "submission_date": "NIL",
            "submission_date_iso": null,
            "skill_assessed": "NIL",
            "is_homework": false,
            "is_completed": false,
            "completed_at": null,
            "created_at": "2026-09-22 06:40:07"
          },
          {
            "id": 444,
            "update_id": 45,
            "date": "2026-09-22",
            "period_number": 4,
            "subject": "English Literature",
            "topic": "The Cat in the Hat",
            "sub_topic": "Movie: The Cat In The Hat",
            "cw": "NIL",
            "reinforcement": "NIL",
            "submission_date": "NIL",
            "submission_date_iso": null,
            "skill_assessed": "NIL",
            "is_homework": false,
            "is_completed": false,
            "completed_at": null,
            "created_at": "2026-09-22 06:40:07"
          },
          {
            "id": 445,
            "update_id": 45,
            "date": "2026-09-22",
            "period_number": 5,
            "subject": "Mathematics",
            "topic": "Subtraction",
            "sub_topic": "Revision",
            "cw": "NIL",
            "reinforcement": "NIL",
            "submission_date": "NIL",
            "submission_date_iso": null,
            "skill_assessed": "NIL",
            "is_homework": false,
            "is_completed": false,
            "completed_at": null,
            "created_at": "2026-09-22 06:40:07"
          },
          {
            "id": 446,
            "update_id": 45,
            "date": "2026-09-22",
            "period_number": 6,
            "subject": "Skill Program",
            "topic": "Financial Literacy",
            "sub_topic": "Recognising Notes and Coins",
            "cw": "NIL",
            "reinforcement": "NIL",
            "submission_date": "NIL",
            "submission_date_iso": null,
            "skill_assessed": "NIL",
            "is_homework": false,
            "is_completed": false,
            "completed_at": null,
            "created_at": "2026-09-22 06:40:07"
          },
          {
            "id": 447,
            "update_id": 45,
            "date": "2026-09-22",
            "period_number": 7,
            "subject": "Skill Program",
            "topic": "Financial Literacy",
            "sub_topic": "Recognising Notes and Coins",
            "cw": "NIL",
            "reinforcement": "NIL",
            "submission_date": "NIL",
            "submission_date_iso": null,
            "skill_assessed": "NIL",
            "is_homework": false,
            "is_completed": false,
            "completed_at": null,
            "created_at": "2026-09-22 06:40:07"
          },
          {
            "id": 448,
            "update_id": 45,
            "date": "2026-09-22",
            "period_number": 8,
            "subject": "Computers",
            "topic": "Meet the Computer Mouse",
            "sub_topic": "Revision worksheet",
            "cw": "NIL",
            "reinforcement": "NIL",
            "submission_date": "NIL",
            "submission_date_iso": null,
            "skill_assessed": "NIL",
            "is_homework": false,
            "is_completed": false,
            "completed_at": null,
            "created_at": "2026-09-22 06:40:07"
          },
          {
            "id": 449,
            "update_id": 45,
            "date": "2026-09-22",
            "period_number": 9,
            "subject": "Social Science",
            "topic": "Animals Around Me",
            "sub_topic": "Animals: Where do they live?",
            "cw": "CWSH-23,24,25",
            "reinforcement": "RW-16,17",
            "submission_date": "28/9/26",
            "submission_date_iso": null,
            "skill_assessed": "NIL",
            "is_homework": true,
            "is_completed": false,
            "completed_at": null,
            "created_at": "2026-09-22 06:40:07"
          },
          {
            "id": 450,
            "update_id": 45,
            "date": "2026-09-22",
            "period_number": 10,
            "subject": "Social Science",
            "topic": "Animals Around Me",
            "sub_topic": "Animals: Where do they live?",
            "cw": "CWSH-23,24,25",
            "reinforcement": "RW-16,17",
            "submission_date": "28/9/26",
            "submission_date_iso": null,
            "skill_assessed": "NIL",
            "is_homework": true,
            "is_completed": false,
            "completed_at": null,
            "created_at": "2026-09-22 06:40:07"
          }
        ]
      },
      {
        "date": "2026-09-23",
        "display_date": "23/09/2026",
        "grade": "Grade - 1F",
        "words_of_the_day": [],
        "teacher_note": "",
        "total_periods": 0,
        "homework_count": 0,
        "completed_homework_count": 0,
        "periods": [],
        "is_empty": true
      },
      {
        "date": "2026-09-24",
        "display_date": "24/09/2026",
        "grade": "Grade - 1F",
        "words_of_the_day": [],
        "teacher_note": "",
        "total_periods": 0,
        "homework_count": 0,
        "completed_homework_count": 0,
        "periods": [],
        "is_empty": true
      },
      {
        "date": "2026-09-25",
        "display_date": "25/09/2026",
        "grade": "Grade - 1F",
        "words_of_the_day": [],
        "teacher_note": "",
        "total_periods": 0,
        "homework_count": 0,
        "completed_homework_count": 0,
        "periods": [],
        "is_empty": true
      }
    ],
    "weekly_dictation_words": [
      "gone",
      "saw",
      "thump",
      "kind"
    ],
    "active_homework_items": [
      {
        "period_id": 17,
        "date": "2026-09-21",
        "period_number": 7,
        "subject": "Robotics",
        "topic": "Project 3: Windy Wonder Machine",
        "reinforcement": "To practice and complete Tinkercad project 3 from pages 25-28",
        "submission_date": "NIL",
        "submission_date_iso": null,
        "is_completed": true
      },
      {
        "period_id": 449,
        "date": "2026-09-22",
        "period_number": 9,
        "subject": "Social Science",
        "topic": "Animals Around Me",
        "reinforcement": "RW-16,17",
        "submission_date": "28/9/26",
        "submission_date_iso": null,
        "is_completed": false
      }
    ]
  },
  "circulars": [
    {
      "id": 19,
      "title": "Viva Junior Champs Circular-Cricket",
      "category": "Sports",
      "publish_date": "2026-09-14",
      "file_url": "",
      "summary": "Interschool cricket tournament information for junior learners covering coaching schedules, matches, and team participation.",
      "is_read": false,
      "created_at": "2026-09-22 06:53:17"
    },
    {
      "id": 18,
      "title": "Viva Junior Champs Circular-Basketball",
      "category": "Sports",
      "publish_date": "2026-09-14",
      "file_url": "",
      "summary": "Interschool basketball tournament details for junior grades emphasizing skills development, team coordination, and match play.",
      "is_read": false,
      "created_at": "2026-09-22 06:53:17"
    },
    {
      "id": 17,
      "title": "Viva Junior Champs Circular-Football",
      "category": "Sports",
      "publish_date": "2026-09-14",
      "file_url": "",
      "summary": "Interschool football championship details for junior students focusing on teamwork, agility, and sportsmanship.",
      "is_read": false,
      "created_at": "2026-09-22 06:53:17"
    },
    {
      "id": 21,
      "title": "Primary Fun Friday",
      "category": "Events",
      "publish_date": "2026-09-10",
      "file_url": "",
      "summary": "Monthly themed Fun Friday interactive activities planned for primary learners on the last Friday of each month. No heavy schoolbags required.",
      "is_read": false,
      "created_at": "2026-09-22 06:53:17"
    },
    {
      "id": 20,
      "title": "Viva 18 Family Fiesta Circular",
      "category": "Events",
      "publish_date": "2026-09-10",
      "file_url": "",
      "summary": "Celebration details for the annual VIVA Family Fiesta celebrating 18 years with creative showcases, games, and community events.",
      "is_read": false,
      "created_at": "2026-09-22 06:53:17"
    },
    {
      "id": 22,
      "title": "Youth Winter Cup Football - Bengaluru (3 Days)",
      "category": "Sports",
      "publish_date": "2026-08-29",
      "file_url": "",
      "summary": "Details regarding the 3-day Youth Winter Cup Football tournament in Bengaluru organized in association with Olympia Sportz & Events.",
      "is_read": false,
      "created_at": "2026-09-22 06:53:17"
    },
    {
      "id": 23,
      "title": "The Stars Ensemble and The Jr. Stars Ensemble",
      "category": "Events",
      "publish_date": "2026-08-12",
      "file_url": "",
      "summary": "Audition and participation circular for the VIVA Stars Ensemble and Junior Stars Ensemble music and cultural showcases.",
      "is_read": false,
      "created_at": "2026-09-22 06:53:17"
    },
    {
      "id": 24,
      "title": "Viva - Announcement and details",
      "category": "Academic",
      "publish_date": "2026-07-01",
      "file_url": "",
      "summary": "Official announcement and participation guidelines for VIBGYOR Viva annual inter-school cultural, sports, and arts fest.",
      "is_read": false,
      "created_at": "2026-09-22 06:53:17"
    },
    {
      "id": 25,
      "title": "Viva - Announcement and details",
      "category": "Academic",
      "publish_date": "2026-06-30",
      "file_url": "",
      "summary": "Official announcement and participation guidelines for VIBGYOR Viva annual inter-school cultural, sports, and arts fest.",
      "is_read": false,
      "created_at": "2026-09-22 06:53:17"
    },
    {
      "id": 26,
      "title": "External Exam Information",
      "category": "Academic",
      "publish_date": "2026-06-15",
      "file_url": "",
      "summary": "Information and schedule for optional external academic competitions and Olympiads (Science, Math, SpellBee) conducted in school.",
      "is_read": false,
      "created_at": "2026-09-22 06:53:17"
    },
    {
      "id": 39,
      "title": "Hubble Orion Parent App \u2013 New Features & Parent User Manual",
      "category": "Admin",
      "publish_date": "2026-05-30",
      "file_url": "https://hubbleorion.hubblehox.com/",
      "summary": "Parent manual introducing new features in Hubble Orion, including daily timetable sync, digital diary updates, and school announcements.",
      "is_read": false,
      "created_at": "2026-09-22 12:07:55"
    },
    {
      "id": 38,
      "title": "External Exam Information",
      "category": "Academic",
      "publish_date": "2026-05-30",
      "file_url": "https://hubbleorion.hubblehox.com/",
      "summary": "Information and schedule for optional external academic competitions and Olympiads (Science, Math, SpellBee) conducted in school.",
      "is_read": false,
      "created_at": "2026-09-22 12:07:55"
    },
    {
      "id": 37,
      "title": "Student Holiday List 26-27",
      "category": "Admin",
      "publish_date": "2026-05-30",
      "file_url": "https://hubbleorion.hubblehox.com/",
      "summary": "Official VIBGYOR academic calendar and scheduled student holiday list for academic year 2026-27, detailing term breaks and national holidays.",
      "is_read": false,
      "created_at": "2026-09-22 12:07:55"
    },
    {
      "id": 36,
      "title": "VH-School Team TRY OUT for New Admissions",
      "category": "Admin",
      "publish_date": "2026-05-30",
      "file_url": "https://hubbleorion.hubblehox.com/",
      "summary": "Tryout schedule and eligibility criteria for students seeking admission to official school sports teams (Basketball, Football, Cricket, etc.).",
      "is_read": false,
      "created_at": "2026-09-22 12:07:55"
    },
    {
      "id": 31,
      "title": "After School Program",
      "category": "Academic",
      "publish_date": "2026-05-30",
      "file_url": "",
      "summary": "Details and enrollment information for post-school activity clubs, sports training, and creative enrichment programs.",
      "is_read": false,
      "created_at": "2026-09-22 06:53:17"
    }
  ]
};
